In [1]:
import hvplot.polars as hv
import polars as pl

# Lab 2

In [2]:
df = pl.read_csv("lab2.csv")
df = df.rename({"": "Subject"})
df

shape: (6, 4)
┌────────────────────────────┬─────────────────┬─────────────────────┬────────────────┐
│ Subject                    ┆ Very interested ┆ Somewhat interested ┆ Not interested │
│ ---                        ┆ ---             ┆ ---                 ┆ ---            │
│ str                        ┆ i64             ┆ i64                 ┆ i64            │
╞════════════════════════════╪═════════════════╪═════════════════════╪════════════════╡
│ Big Data (Spark / Hadoop)  ┆ 1332            ┆ 729                 ┆ 127            │
│ Data Analysis / Statistics ┆ 1688            ┆ 444                 ┆ 60             │
│ Data Journalism            ┆ 429             ┆ 1081                ┆ 610            │
│ Data Visualization         ┆ 1340            ┆ 734                 ┆ 102            │
│ Deep Learning              ┆ 1263            ┆ 770                 ┆ 136            │
│ Machine Learning           ┆ 1629            ┆ 477                 ┆ 74             │
└────────────────────────────┴─────────────────┴─────────────────────┴────────────────┘

In [3]:
df_sorted = df.sort(by="Very interested", descending=True)
df_sorted

shape: (6, 4)
┌────────────────────────────┬─────────────────┬─────────────────────┬────────────────┐
│ Subject                    ┆ Very interested ┆ Somewhat interested ┆ Not interested │
│ ---                        ┆ ---             ┆ ---                 ┆ ---            │
│ str                        ┆ i64             ┆ i64                 ┆ i64            │
╞════════════════════════════╪═════════════════╪═════════════════════╪════════════════╡
│ Data Analysis / Statistics ┆ 1688            ┆ 444                 ┆ 60             │
│ Machine Learning           ┆ 1629            ┆ 477                 ┆ 74             │
│ Data Visualization         ┆ 1340            ┆ 734                 ┆ 102            │
│ Big Data (Spark / Hadoop)  ┆ 1332            ┆ 729                 ┆ 127            │
│ Deep Learning              ┆ 1263            ┆ 770                 ┆ 136            │
│ Data Journalism            ┆ 429             ┆ 1081                ┆ 610            │
└────────────────────────────┴─────────────────┴─────────────────────┴────────────────┘

In [14]:
plotter = hv.hvPlotTabularPolars(df_sorted)

plot = plotter.bar(
    x="Subject",
    # y=["Very interested", "Somewhat interested", "Not interested"],
    xlabel="Subject",
    ylabel="Interested",
    legend=True,
    height=540,
    width=1200
)

plot

:Bars   [Subject,Variable]   (value)

# Lab 3