In [ ]:
import polars as pl

In [4]:
df = pl.read_csv("./lab2.csv")
df

shape: (6, 4)
┌────────────────────────────┬─────────────────┬─────────────────────┬────────────────┐
│                            ┆ Very interested ┆ Somewhat interested ┆ Not interested │
│ ---                        ┆ ---             ┆ ---                 ┆ ---            │
│ str                        ┆ i64             ┆ i64                 ┆ i64            │
╞════════════════════════════╪═════════════════╪═════════════════════╪════════════════╡
│ Big Data (Spark / Hadoop)  ┆ 1332            ┆ 729                 ┆ 127            │
│ Data Analysis / Statistics ┆ 1688            ┆ 444                 ┆ 60             │
│ Data Journalism            ┆ 429             ┆ 1081                ┆ 610            │
│ Data Visualization         ┆ 1340            ┆ 734                 ┆ 102            │
│ Deep Learning              ┆ 1263            ┆ 770                 ┆ 136            │
│ Machine Learning           ┆ 1629            ┆ 477                 ┆ 74             │
└────────────────────────────┴─────────────────┴─────────────────────┴────────────────┘

In [5]:
df = df.sort("Very interested", descending=True)
df

shape: (6, 4)
┌────────────────────────────┬─────────────────┬─────────────────────┬────────────────┐
│                            ┆ Very interested ┆ Somewhat interested ┆ Not interested │
│ ---                        ┆ ---             ┆ ---                 ┆ ---            │
│ str                        ┆ i64             ┆ i64                 ┆ i64            │
╞════════════════════════════╪═════════════════╪═════════════════════╪════════════════╡
│ Data Analysis / Statistics ┆ 1688            ┆ 444                 ┆ 60             │
│ Machine Learning           ┆ 1629            ┆ 477                 ┆ 74             │
│ Data Visualization         ┆ 1340            ┆ 734                 ┆ 102            │
│ Big Data (Spark / Hadoop)  ┆ 1332            ┆ 729                 ┆ 127            │
│ Deep Learning              ┆ 1263            ┆ 770                 ┆ 136            │
│ Data Journalism            ┆ 429             ┆ 1081                ┆ 610            │
└────────────────────────────┴─────────────────┴─────────────────────┴────────────────┘